server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: 192.168.0.239:8846
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.106.121.52:3306/seata_order
    username: root
    password: mz666

feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: debug

mybatis:
  mapperLocations: classpath:mapper/*.xml